### ISSUE TITLE
pip install mscheck failing due to typo?

### ISSUE THREAD

**Issue by maddyboo** [Waztom/mscheck#3]
After the pip install requirements were changed, when following step 3 of MScheck installation on a fresh conda environment I get a dependencies error:

Command: 
`pip install mscheck`

Result:
```
[...]
The conflict is caused by:
    mscheck 0.2.5b0 depends on pyopenms-nighly
    mscheck 0.2.4b0 depends on pyopenms==2.6.0
[...]
```

I can install all the other requirements manually without issue. Therefore I wonder is the nighly/nightly typo on line 34 the source of the issue? I don't have much experience of deconvoluting pip conflict errors... 

https://github.com/Waztom/mscheck/blob/32aa889ece6934b411803b6858f58e216feb542e/setup.py#L34

Thanks!

**Comment by Waztom** [comment]
@maddyboo can you please give it another go? Unable to get pyopenms to install via pip as a dep for mscheck. Updated the README to install pyopenms with a pip index-URL before pip installing mscheck.

**Comment by maddyboo** [comment]
All good! Installing smoothly again, many thanks @Waztom !
